### PR TITLE
Port to SDL 2

### PR DESCRIPTION
**Pull request by ahockersten**
This ports Liero to SDL 2. Obviously, this is not well-tested yet (I made it in an afternoon, give me a break :)), but in my extremely limited testing it seems to work fine. On Linux, that is. I have not tested Windows yet, and I have no capability of testing on Mac. I'm pretty sure Mac is broken by this patch, see:
https://wiki.libsdl.org/MigrationGuide

This is based on my single screen replay patch, mostly because I was working on Linux and needed the compile fixes on that branch. The overlap is very small though, so if you want I can rebase this on master.

Benefits of this patch:
- it has a proper implementation of vertical sync that should sync much better with the hardware. No more annoying occasional stuttering! Edit: I'm full of horse manure, I still see stuttering on my machine unfortunately.
- fullscreen is now fullscreen-in-a-window (aka borderless fullscreen). This removes the annoying time to switch between the modes on modern screens. Also, this means we control the scaling instead of the monitor - this gives much better results on most monitors. It wouldn't be hard to support "proper" fullscreen as well, but I dislike adding options if no one will use them (let's see if someone complains before adding proper fullscreen?)
- drawspeed is greatly improved on modern hardware due to using the GPU. The only place where I think this matters is on the stats screen. Edit: actually, this seems to be untrue.

Drawbacks of this patch:
- vsync can no longer be disabled (but disabling it was broken when I tested it anyway)
- fullscreen resolution can no longer be changed. It always uses whatever your OS uses (but if you can run an OS at a given resolution, surely you can run Liero?)
- SDL 2 possibly requires slightly more modern hardware

I'm not just doing this "for fun" btw. My next step is adding support for a separate spectator window, and SDL 1.2 does not have support for multiple windows.

### CODE REVIEW

**Comment by ahockersten** [comment]
Windows now compiles and runs.

**Comment by ahockersten** [comment]
Bah, looks like I need to rewrite the keyboard input before this can be merged.

**Comment by ahockersten** [comment]
Keyboard input is fixed.

**Comment by ahockersten** [comment]
I haven't tested joystick input on this branch. I should confirm that it works before it gets merged.

**Comment by ahockersten** [comment]
Joystick input worked when I tested.

Some patches are missing on this branch, they have gone into spectator_window instead. I can backport them if you want to merge one without the other

**Comment by emlai** [comment]
Works flawlessly on Mac. This also fixes a horrible slowdown when playing in a maximized window. I hope this gets merged soon.

**Pull request closed without merging**
