### PR TITLE
Github actions for building and releasing

### PR DESCRIPTION
**Pull request by ahockersten**
This is a PR for building and releasing using Github Actions. It will trigger a build whenever a push happens on any branch (e.g. a PR), and a release whenever a push happens on the "master" branch.

Current status:
- Windows works and emits a working artifact as well as a runnable release (tested on my Windows 11 machine). This release includes copies of the required SDL2.dll and SDL2_image.dll files (as well as their respective copyright notices).
- Ubuntu works and emits a working artifact as well as a runnable release (tested on my Arch Linux machine)
- MacOS doesn't work. I suspect this is a pre-existing issue but I don't know much about MacOS development (and I don't have a Mac) so I don't know how to debug it. I have disabled the code for building MacOS until someone who knows how to solve this can look into it. Maybe @emlai is interested? :angel: 

This also fixes two unrelated bugs:
- My previous ARM support patch was not complete, I probably forgot to copy some files when working on my Pi. I found this when debugging MacOS builds
- The change to use "openliero" packages didn't work in Linux, since it requires lowercase filenames, so I just renamed the files 

Known issues:
- the produced executables do not get the executable bit set for the Ubuntu builds. I'm not sure if Github Actions artifacts support this. The generated release .tar.xz file does set permissions correctly 
- MacOS doesn't work, see above

My suggestion is to merge with the above issues remaining.

Examples of builds: https://github.com/ahockersten/liero/actions?query=branch%3Abuild-actions

Example of a release. This has the wrong naming since the branch built is named "build-actions". This would be named "master-a7d53c4b1ef964c4f0f652e5d503e50d7e98316a": https://github.com/ahockersten/liero/releases/tag/build-actions-a7d53c4b1ef964c4f0f652e5d503e50d7e98316a

### CODE REVIEW

**Comment by ahockersten** [comment]
Examples of builds can be found in my repo: https://github.com/ahockersten/liero/actions?query=branch%3Abuild-actions

**Comment by grawlinson** [comment]
I've got a M1 Air so I can do a bit of hacking on the macOS side, we may have to move this repo over to github.com/openliero because I think gliptic only gave me basic repository permissions (i.e. no CI/GHA or anything like that).

EDIT: I'll probably just setup the relevant repos (not sure when, quite busy IRL) on openliero, copy this repo over & mirror the changes made over on openliero.

**Comment by ahockersten** [comment]
I can setup the repo on openliero/openliero if you'd like? I have plenty of time now but it's a bit unclear how much time and energy I will have for hacking on Liero once I start my new job in September. :)

**Comment by grawlinson** [comment]
> I can setup the repo on openliero/openliero if you'd like? I have plenty of time now but it's a bit unclear how much time and energy I will have for hacking on Liero once I start my new job in September. :)

Go for it!

**Comment by grawlinson** [comment]
I’ve just imported the lierolibre repositories (from gitlab) under the openliero organization because there’s no guarantee that the repositories will be around. Think of it as keeping them around for archival/reference purposes.

**Comment by ahockersten** [comment]
[openliero/openliero](https://github.com/openliero/openliero/)  has been created, and I have merged this PR there.

Unfortunately the repo does not seem to have permissions to create releases for itself (and I can't give the repository that permission either, probably this is a github setting on the organization level).

**Comment by ahockersten** [comment]
Closing this as I merged into openliero/openliero instead.

**Pull request closed without merging**
